[package]
name = "nxs_interface_macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.29"
syn = { version="1.0.77", features=["extra-traits"] }
quote = "1.0.9"
parse-display = { version="0.5.1", features=["std"], default-features=false }
